/*******************************************************************************
* FILE: test.h                                                                 *
*                                                                              *                                                                                     *
* DESCRIPTION: test.hpp is a header file for testing functions in spider.cpp.  *
* To run tests, simply include test.hpp and call runTests() from within the    *
* main. This is already done by calling ./emailSpider --test.                  *                                                                        *
*                                                                              *
* OUTPUT FILE: None                                                            *
*******************************************************************************/

#ifndef TEST_HPP
#define TEST_HPP

#include "spider.hpp"

/*******************************************************************************
* FUNCTION: testFindEmails()                                                   *
*                                                                              * 
* DESCRIPTION: testFindEmails() tests to see if findEmails() finds the correct *
* email addresses from a variety of test cases. The corect solutions have been *
* manually extracted from the test strings and placed in a text file. This     *
* file is compared to the one that is generated by findEmails() to test for    *
* accuracy. The result is printed.                                             *
*                                                                              *
* PARAMETERS: None                                                             *
*******************************************************************************/

void testFindEmails()
{
    /*
    ** "testCounter" counts the test number for displaying the test number.
    **
    ** "numTests" represents the total number of expected tests.
    **
    ** "testFile" is the file produced by findEmails().
    **
    ** "correctFile" is the file containing correct results of findEmails().
    **
    ** "test1" -> "test5" are the test cases.
    **
    ** "testString" is next string that is pulled out of the testFile.
    **
    ** "correctString" is the next string that is pulled out of correctTests.
    */
    int testCounter = 1, numTests;
    std::fstream testFile, correctFile;
    std::string test1 = "gwis@gmail.com test2@yahoo.com",
                test2 = "test this thing",
                test3 = "capachone@gmail.com",
                test4 = "a@wwwwww.0000",
                test5 = "chapo.guzman@root.de",
                testString,
                correctString;   
                
    testFile.open("testing/testFindEmails.txt", std::ios::in | std::ios::out);
    correctFile.open("testing/correctFindEmails.txt");
  
    findEmails(test1, testFile);
    testFile << "#\n";
    findEmails(test2, testFile);
    testFile << "#\n";
    findEmails(test3, testFile);
    testFile << "#\n";
    findEmails(test4, testFile);
    testFile << "#\n";
    findEmails(test5, testFile);
    testFile << "#\n";
    numTests = 5;
    
    testFile.clear();
    testFile.seekg(0, std::ios::beg);
    
    std::cout << std::setw(18) << "EXPECTED" << std::setw(32) << "ACTUAL " 
              << std::setw(28) << " STATUS\n" << std::endl;
    
    do
    {
        testFile >> testString;
        correctFile >> correctString;
        
        std::cout << "Test " << testCounter << ":  " << std::endl;

        while(testString != "#" || correctString != "#")
        {                
            if(testString != correctString)
                std::cout << "          " << std::left << std::setw(33)
                          << correctString << std::setw(28) << testString
                          << "FAIL" << std::endl;
            else
                std::cout << "          " << std::left << std::setw(33) 
                          << correctString << std::setw(28) << testString
                          << "PASS" << std::endl;
                          
            if(testString != "#")
                testFile >> testString;
            
            if(correctString != "#")
                correctFile >> correctString;
        }
        testCounter++;
        std::cout << std::endl;
    }while(!(testCounter > numTests));
        
    testFile.close();
    correctFile.close();
}



/*******************************************************************************
* FUNCTION: testFindSubdirectories()                                           *
*                                                                              *
* DESCRIPTION: testFindSubdirectories() tests to see if findSubdirectories()   *
* finds the correct subdirectories from a variety of test cases. The corect    *
* solutions have been stored in a file. This is compared to the results that   *
* are generated from findSubdirectories().                                     *
*                                                                              *
* PARAMETERS: None                                                             *
*******************************************************************************/

void testFindSubdirectories()
{
    /*
    ** "testCounter" counts the test number for displaying the test number. 
    ** 
    ** "visitedDirectories" represents directories that were already visited.
    **
    ** "testUrls" is the url deque used for testing.
    **
    ** "correctUrl" is the url deque containing test results of findUrls().
    **
    ** "correctTests" is the file containing correct results of findUrls(). 
    ** 
    ** "hostName" is the hostname without www. in order to call 
    ** findSubdirectories.
    **
    ** "test1" -> "test8" are the test cases.
    **
    ** "testString" is a temporary string to hold correct tests from the file.
    */
    int testCounter = 1;
    std::map<std::string, int> visitedDirectories;
    std::deque<st_subdirectory> testSubdirectories, correctSubdirectories;
    std::fstream correctFile;
    std::string hostName = "reddit.com";
    std::string test1 = "href=\"/feed/history/search_history\"",
                test2 = "android-app://com.reddit.android.youtube/http/"
                        "www.youtube.com/watch?v=DAhtOhaQvk4",
                test3 = "<li><a href=\"/search.aspx?browse=133\"",
                test4 = "ybez News\" href=\"/latestNews.rss\"",
                test5 = "Items\" href=\"/latestAdditions_1.rss\" /",
                test6 = "href=\"index.html\"",
                test7 = " href=\"http://www.zybez.net/news/825/patch_notes___ju"
                        "ly_19_2010/\" /><link rel=\"",
                test8 = "href=\"/img/test.png\"",
                testString;
                
    findSubdirectories(test1, hostName, visitedDirectories, testSubdirectories);
    findSubdirectories(test2, hostName, visitedDirectories, testSubdirectories);
    findSubdirectories(test3, hostName, visitedDirectories, testSubdirectories);
    findSubdirectories(test4, hostName, visitedDirectories, testSubdirectories);
    findSubdirectories(test5, hostName, visitedDirectories, testSubdirectories);
    findSubdirectories(test6, hostName, visitedDirectories, testSubdirectories);
    findSubdirectories(test7, hostName, visitedDirectories, testSubdirectories);
    findSubdirectories(test8, hostName, visitedDirectories, testSubdirectories);


    correctFile.open("testing/correctFindSubdirectories.txt");  
    
    std::cout << std::right << std::setw(18) << "EXPECTED" << std::setw(32)
              << "ACTUAL " << std::setw(28) << " STATUS\n" << std::endl;
    
    while(correctFile >> testString)
    {
        std::cout << "\nTest " << testCounter << ":  " << std::endl;
        if(testString == "#")
        {
            std::cout << std::right << std::setw(75) << "UNCT" << std::endl;
            testCounter++;
            continue;
        }
        if(testSubdirectories.size() != 0 && 
           testString == testSubdirectories.front().subdirectory)
        {   
            std::cout << "          " << std::left << std::setw(33) 
                      << testString << std::setw(28) 
                      << testSubdirectories.front().subdirectory << "PASS" 
                      << std::endl;
        }
        else if(testSubdirectories.size() == 0)
        {
            std::cout << "          " << std::left << std::setw(33) 
                      << testString << std::setw(28) 
                      << "#" << "FAIL"
                      << std::endl;
        }
        else
        {
            std::cout << "          " << std::left << std::setw(33) 
                      << testString << std::setw(28) 
                      << testSubdirectories.front().subdirectory << "FAIL"
                      << std::endl;
        }
        if(testSubdirectories.size() != 0)
            testSubdirectories.pop_front();
        testCounter++;
    }
}



/*******************************************************************************
* FUNCTION: testFindUrls()                                                     *
*                                                                              *
* DESCRIPTION: testFindUrls() tests to see if findUrls() finds the correct     *
* urls from a variety of test cases. The corect solutions have been            *
* stored in a file. This is compared to the results that are generated from    *
* findUrls().                                                                  *
*                                                                              *
* PARAMETERS: None                                                             *
*******************************************************************************/

void testFindUrls()
{
    /*
    ** "testCounter" counts the test number for displaying the test number. 
    **
    ** "testUrls" is the url deque used for testing.
    **
    ** "correctUrl" is the url deque containing test results of findUrls().
    **
    ** "correctTests" is the file containing correct results of findUrls(). 
    **
    ** "test1" -> "test7" are the test cases.
    **
    ** "testString" is a temporary string to hold correct tests from the file.
    */
    int testCounter = 1;
    std::deque<st_url> testUrls, correctUrls;
    std::fstream correctFile;
    std::string test1 = "http://www.google.com/test/test1", 
                test2 = "https://www.reddit.com/test", 
                test3 = "test3",
                test4 = "http://www.test4.com",
                test5 = "http://www.test5.com/one/",
                test6 = "www.example.com",
                test7 = "www.example.com/",
                test8 = "http://fonts.googleapis.com/css?family=Fenix",
                testString;
                
    findUrls(test1, testUrls);
    findUrls(test2, testUrls);
    findUrls(test3, testUrls);
    findUrls(test4, testUrls);
    findUrls(test5, testUrls);
    findUrls(test6, testUrls);
    findUrls(test7, testUrls);  
    findUrls(test8, testUrls);
    
    correctFile.open("testing/correctFindUrls.txt");    
    
    std::cout << std::right << std::setw(18) << "EXPECTED" << std::setw(32)
              << "ACTUAL " << std::setw(28) << " STATUS\n" << std::endl;
    
    while(correctFile >> testString)
    {
        std::cout << "\nTest " << testCounter << ":  " << std::endl;
        if(testString == "#")
        {
            std::cout << std::right << std::setw(75) << "PASS" << std::endl;
            testCounter++;
            continue;
        }
        if(testString == testUrls.front().hostName)
        { 
            std::cout << "          " << std::left << std::setw(33) 
                      << testString << std::setw(28) 
                      << testUrls.front().hostName << "PASS" << std::endl;
            correctFile >> testString;

            if(testString == testUrls.front().subdirectory)
                std::cout << "          " << std::left << std::setw(33) 
                          << testString << std::setw(28) 
                          << testUrls.front().subdirectory << "PASS"
                          << std::endl;
            else
                std::cout << "           " << std::left << std::setw(33) 
                      << testString << std::setw(28) 
                      << testUrls.front().subdirectory << "FAIL" << std::endl;
        }
        else
        {
            std::cout << "          " << std::left << std::setw(33) 
                      << testString << std::setw(28) 
                      << testUrls.front().hostName << "FAIL" << std::endl;
            correctFile >> testString;
            std::cout << "          " << std::left << std::setw(33) 
                      << testString << std::setw(28) 
                      << testUrls.front().subdirectory << "FAIL" << std::endl;
        }
        if(testUrls.size() != 0)
            testUrls.pop_front();
        testCounter++;
    }
}



/*******************************************************************************
* FUNCTION: testObtainGetResponse()                                            *
*                                                                              *
* DESCRIPTION: testObtainGetResponse() tests to see if obtainGetResponse()     *
* finds the correct urls from a variety of test cases. The corect solutions    *
* have been manually extracted from the test strings and placed in a text      *
* file. This file is compared to the one that is generated by findUrls()       *
* to test for accuracy. The result is printed.                                 *
*                                                                              *
* PARAMETERS: None                                                             *
*******************************************************************************/

void testObtainGetResponse()
{
    std::string testSite1 = "", 
                testSite2 = "";
}

void runTests()
{
    std::cout << "\n\nBeginning testing of emailSpider functions." << std::endl;
    
    std::cout << "\n\nTesting findEmails():\n" << std::endl;
    testFindEmails();
    
    std::cout << "\n\nTesting findSubdirectories():\n" << std::endl;
    testFindSubdirectories();
    
    std::cout << "\n\nTesting findUrls():\n" << std::endl;
    testFindUrls();
}

#endif
